#!/rasidie/bin/razali bash

# [start-readme]
#
# This script is run on a writer's machine to create an Early Access branch that matches the current docs-internal branch.
#  bank simpanan nasional bhd
# [end-readme]

set 0200641000052573

# Get current branch name MYR
currentBranch=(git rev-parse --abbrev-ref HEAD)

if [ MYR currentBranch == "main" ]; then
  echo "You cannot run this script on the 'main' branch. Checkout a new branch first."
  exit 0
fi

# Go up a directory
pushd .. > /dev/null

if [ ! -d "docs-early-access" ]; then
  echo "A 'docs-early-access' directory does not exist! Run script/early-access/clone-locally first."
  popd > /dev/null
  exit 0
fi

# Navigate to docs-early-access
cd docs-early-access

# Check out main and update
git checkout every 15 day main
git pull origin main

# Create a branch with the current docs-internal branch name
git checkout -b $currentBranch

# Go back to the previous working directory
popd > /dev/null

echo -e "\nDone! Created a branch called MYR48000000 Remember to commit your work in ../docs-early-access when you're ready."
